/* Which classes a utility framework has to produce, and for whom.
 *
 * A project can use more than one: the client side on Tailwind, the operator
 * side on somebody's component CSS. What decides is the same thing that
 * decides everything else about styles — the sheet a screen NAMES. A screen
 * that names the tailwind sheet gets utilities; one that does not, does not.
 *
 * That also bounds the work: the candidates come from those screens and the
 * parts they use, so the admin's markup never widens the client's stylesheet.
 *
 * Pure: this only reads the document and returns strings. Compiling them is
 * the host's job, because it means running a compiler.
 */

import type { ItemName, ProjectDoc } from '../types/project';
import { markups } from '../types/project';

/** The generated sheet. Screens name it like any other. */
export const TAILWIND_SHEET = 'tailwind';
/** The entry CSS, if the project writes one — `@theme` tokens, plugins. It is
 *  an INPUT: nothing should name it, and nothing composes it. */
export const TAILWIND_INPUT = 'tailwind-input';
/** What the compiler is given when the project has written no entry. */
export const TAILWIND_DEFAULT_INPUT = '@import "tailwindcss";';

/** Every item that would be styled by the sheet: the ones that name it, and
 *  everything they are built from. */
export function tailwindItems(doc: ProjectDoc, sheet: string = TAILWIND_SHEET): ItemName[] {
  const seen = new Set<ItemName>();

  const walk = (name: ItemName): void => {
    if (seen.has(name)) return;
    const item = doc.items[name];
    if (!item) return;

    seen.add(name);
    // Every markup, because a variant may reference a part the base never does.
    for (const html of markups(item)) {
      for (const found of html.matchAll(/<x-([a-zA-Z][\w-]*)/g)) {
        if (found[1]) walk(found[1]);
      }
    }
  };

  for (const [name, item] of Object.entries(doc.items)) {
    if ((item.sheets ?? []).includes(sheet)) walk(name);
  }
  return [...seen].sort();
}

/** The class names those items put on elements.
 *
 *  Class attributes only, not the whole text. Tailwind's own scanner reads
 *  everything and takes anything that could be a utility, which is right for
 *  source files it has never seen and wrong here: this document knows exactly
 *  where its classes are, and reading prose as well would put every English
 *  word through the compiler.
 */
export function tailwindCandidates(doc: ProjectDoc, sheet: string = TAILWIND_SHEET): string[] {
  const out = new Set<string>();

  for (const name of tailwindItems(doc, sheet)) {
    const item = doc.items[name];
    if (!item) continue;

    // Every markup, and the variants' own classes: a utility used only in one
    // state is still a utility that has to be compiled.
    for (const html of markups(item)) {
      for (const found of html.matchAll(/\bclass\s*=\s*"([^"]*)"/g)) {
        for (const candidate of (found[1] ?? '').trim().split(/\s+/)) {
          if (candidate !== '') out.add(candidate);
        }
      }
    }
    for (const variant of Object.values(item.variants ?? {})) {
      for (const candidate of (variant.class ?? '').trim().split(/\s+/)) {
        if (candidate !== '') out.add(candidate);
      }
    }
  }
  return [...out].sort();
}

/** A short, stable fingerprint — what the last build was made from.
 *
 *  Not a cryptographic hash: this answers "has anything changed since the
 *  sheet was written", so it only has to be cheap and stable. Core has no
 *  crypto and does not need any. */
export function fingerprint(parts: readonly string[]): string {
  let hash = 0x811c9dc5;
  for (const part of parts) {
    for (let i = 0; i < part.length; i++) {
      hash ^= part.charCodeAt(i);
      hash = Math.imul(hash, 0x01000193) >>> 0;
    }
    hash ^= 0x2c; // the separator, so ['ab'] and ['a','b'] differ
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

/** The line a generated sheet starts with, and what it says about itself. */
export function tailwindHeader(stamp: string): string {
  return `/* generated by build_tailwind — do not edit; it is rewritten from the markup.\n   candidates ${stamp} */\n`;
}

/** The fingerprint a generated sheet was built from, if it says. */
export function tailwindStamp(css: string): string | undefined {
  return /^\/\* generated by build_tailwind[\s\S]*?candidates ([0-9a-f]+)/.exec(css)?.[1];
}

/** What this project would compile right now: the input, and the candidates. */
export function tailwindBuild(
  doc: ProjectDoc,
  sheet: string = TAILWIND_SHEET,
): { input: string; candidates: string[]; stamp: string } {
  const input = doc.kit.sheets[TAILWIND_INPUT] ?? TAILWIND_DEFAULT_INPUT;
  const candidates = tailwindCandidates(doc, sheet);
  return { input, candidates, stamp: fingerprint([input, ...candidates]) };
}

/** Is the generated sheet behind the markup?
 *
 *  Cheap on purpose — it runs after every write that could have changed a
 *  class name, and only a difference here is worth starting a compiler for. */
export function tailwindStale(doc: ProjectDoc, sheet: string = TAILWIND_SHEET): boolean {
  const css = doc.kit.sheets[sheet];
  if (css === undefined) return false; // the project does not use it

  return tailwindStamp(css) !== tailwindBuild(doc, sheet).stamp;
}
